# Generated by Django 6.0.5 on 2026-05-31 15:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('fraud_typology', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=20)),
                ('fraud_detection_engine_notes', models.JSONField(default=dict)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_cases', to='api.session')),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('card_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('merchant_name', models.CharField(max_length=255)),
                ('merchant_category', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person'), ('atm', 'ATM')], max_length=20)),
                ('cardholder_country', models.CharField(max_length=2)),
                ('merchant_country', models.CharField(max_length=2)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.session')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FraudCaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_transactions', to='api.fraudcase')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_transactions', to='api.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='fraudcase',
            name='transactions',
            field=models.ManyToManyField(related_name='fraud_cases', through='api.FraudCaseTransaction', to='api.transaction'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['session', '-timestamp'], name='api_transac_session_083cce_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['card_id'], name='api_transac_card_id_d7a75a_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcasetransaction',
            index=models.Index(fields=['fraud_case'], name='api_fraudca_fraud_c_eb9922_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcasetransaction',
            index=models.Index(fields=['transaction'], name='api_fraudca_transac_88fe94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fraudcasetransaction',
            unique_together={('fraud_case', 'transaction')},
        ),
        migrations.AddIndex(
            model_name='fraudcase',
            index=models.Index(fields=['session', '-risk_score'], name='api_fraudca_session_bfcea6_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcase',
            index=models.Index(fields=['status'], name='api_fraudca_status_2200e7_idx'),
        ),
    ]
